// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "a5bdb5d6-aaaf-4c0d-8702-252a1c4dd647");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1630220553);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1630220553);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1630220550);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{55a612d0-184f-4a22-b27b-0d56046ad3c4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1630220553);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1630220554083");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1630242154083");
user_pref("browser.search.region", "KR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1630220552");
user_pref("browser.startup.homepage_override.buildID", "20210804193234");
user_pref("browser.startup.homepage_override.mstone", "91.0");
user_pref("browser.startup.lastColdStartupCheck", 1630220552);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1630220553974");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "91.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "KR");
user_pref("dom.push.userAgentID", "69e964846faa4b5582a206e8acb3598b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210804193234");
user_pref("extensions.lastAppVersion", "91.0");
user_pref("extensions.lastPlatformVersion", "91.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"1dc7c782-1483-4bd3-a29a-5c097d47b69f\",\"formautofill@mozilla.org\":\"08dea613-4252-4c03-acac-60d0d3693c1e\",\"pictureinpicture@mozilla.org\":\"f83c378a-3a33-4358-9752-23d9d9f26b52\",\"screenshots@mozilla.org\":\"f915e46b-8f28-45aa-988f-73e59ff0e4e4\",\"webcompat-reporter@mozilla.org\":\"e1f096f5-06ba-4f45-b4b0-6bf630293e19\",\"webcompat@mozilla.org\":\"5fec4e26-edf3-4abc-9e29-bad80b54be8f\",\"default-theme@mozilla.org\":\"3f62d027-f1ba-4ac0-b73a-0a3a5a5acb56\",\"google@search.mozilla.org\":\"e4238dfc-9e8a-46b8-b89c-18b75472c4fb\",\"amazondotcom@search.mozilla.org\":\"e2cc834a-584d-44b4-9d1d-18b6b69a4cf3\",\"wikipedia@search.mozilla.org\":\"9c2aad2b-5766-41ab-95b2-96508cf78b95\",\"bing@search.mozilla.org\":\"7f59256a-3c72-4769-abb3-fc9ee66bd36b\",\"ddg@search.mozilla.org\":\"decc4841-5da6-42d9-9c4d-5cb6ed969ca7\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1630220553);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f72fc1d8-a8f1-4544-82ac-590ad70fae05");
user_pref("toolkit.startup.last_success", 1630220549);
user_pref("toolkit.telemetry.cachedClientID", "91ce33f4-f361-4cda-b471-b01d3d377e23");
user_pref("toolkit.telemetry.previousBuildID", "20210804193234");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
