;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	ignore
	indent-for-tab-command
	mouse-set-region
	python-shell-send-region
	set-rectangular-region-anchor
	))

(setq mc/cmds-to-run-once
      '(
	LaTeX-babel-insert-hyphen
	TeX-insert-sub-or-superscript
	compose-mail
	kill-region
	))
